SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Daemon to multiplex and demultiplex an OSS device
SBOM_LICENSE=	BSD-2-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/virtual_oss/virtual_oss
SBOM_URL=	https://www.FreeBSD.org
