SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control physical system video console devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/conscontrol
SBOM_URL=	https://www.FreeBSD.org
