SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Check the syntax of the group file
SBOM_LICENSE=	LicenseRef-scancode-bsd-unchanged
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/chkgrp
SBOM_URL=	https://www.FreeBSD.org
