SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display disk space occupied by each user
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/quot
SBOM_URL=	https://www.FreeBSD.org
