SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Manage VALE network switches provided by netmap
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/valectl
SBOM_URL=	https://www.FreeBSD.org
