SBOM_NAME=	${PACKAGE}
SBOM_DESC=	List IDs of all processes that have one or more files open
SBOM_LICENSE=	BSD-2-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/fstat
SBOM_URL=	https://www.FreeBSD.org
