SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Send ICMP or ICMPv6 ECHO_REQUEST packets to network hosts
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ping
SBOM_URL=	https://www.FreeBSD.org
