SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control utility for disk mount verification GEOM class
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/geom/mountver
SBOM_URL=	https://www.FreeBSD.org
