SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Userland API library for kernel GEOM subsystem
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libgeom
SBOM_URL=	https://www.FreeBSD.org
