SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Erase device blocks that have no needed contents
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/trim
SBOM_URL=	https://www.FreeBSD.org
