SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure a built-in Ethernet switch
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/etherswitchcfg
SBOM_URL=	https://www.FreeBSD.org
