SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Generates hashed conversion data for iconv(3)
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/mkcsmapper
SBOM_URL=	https://www.FreeBSD.org
