SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Dump ISO-9660 El Torito boot catalog information
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/etdump
SBOM_URL=	https://www.FreeBSD.org
