SBOM_NAME=	${PACKAGE}
SBOM_DESC=	PC Card and Cardbus (PCMCIA) CIS display tool
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/dumpcis
SBOM_URL=	https://www.FreeBSD.org
