SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Send Wake on LAN frames to hosts on a local Ethernet network
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/wake
SBOM_URL=	https://www.FreeBSD.org
