SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Run a command with a different MAC process label
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/setpmac
SBOM_URL=	https://www.FreeBSD.org
