SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Send L2CAP ECHO_REQUEST to remote devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/l2ping
SBOM_URL=	https://www.FreeBSD.org
