SBOM_NAME=	${PACKAGE}
SBOM_DESC=	GEOM Gate network client and control utility
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ggate/ggatec
SBOM_URL=	https://www.FreeBSD.org
