SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Saves and restores information for NAT and state tables.
SBOM_LICENSE=	LicenseRef-scancode-other-permissive
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ipf/ipfs
SBOM_URL=	https://www.FreeBSD.org
