SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Perform actions according to USB HID controls
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/usbhidaction
SBOM_URL=	https://www.FreeBSD.org
