SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Clear locks held on behalf of an NFS client
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/clear_locks
SBOM_URL=	https://www.FreeBSD.org
