SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Protect processes from being killed when swap space is exhausted
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/protect
SBOM_URL=	https://www.FreeBSD.org
