SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Daemon handling autofs mount requests
SBOM_LICENSE=	BSD-2-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/autofs
SBOM_URL=	https://www.FreeBSD.org
