SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Generate lineprinter ripple pattern
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/lpr/lptest
SBOM_URL=	https://www.FreeBSD.org
