SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Resize files or manage file space
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/truncate
SBOM_URL=	https://www.FreeBSD.org
