SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Unload a file from the kernel
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/kldunload
SBOM_URL=	https://www.FreeBSD.org
