SBOM_NAME=	${PACKAGE}
SBOM_DESC=	PC slice table maintenance utility
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/fdisk
SBOM_URL=	https://www.FreeBSD.org
