SBOM_NAME=	${PACKAGE}
SBOM_DESC=	clone of System V curses panel library
SBOM_LICENSE=	X11
SBOM_SOURCE=	https://invisible-island.net/archives/ncurses/ncurses-6.5.tar.gz
SBOM_URL=	https://invisible-island.net/ncurses
SBOM_VERSION=	6.5
