SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Tell ypbind(8) which NIS server process to use
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/ypset
SBOM_URL=	https://www.FreeBSD.org
