SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Connection utility for Option based devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/uhsoctl
SBOM_URL=	https://www.FreeBSD.org
