SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Copy public keys to a remote host
SBOM_LICENSE=	LicenseRef-scancode-bsd-unchanged
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ssh-copy-id
SBOM_URL=	https://www.FreeBSD.org
