SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Who is logged in to machines on local network
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/rusers
SBOM_URL=	https://www.FreeBSD.org
