SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Pass mouse data to the console driver
SBOM_LICENSE=	BSD-2-Clause AND MIT
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/moused/moused
SBOM_URL=	https://www.FreeBSD.org
