SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Virtual bluetooth speaker
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/virtual_oss/virtual_bt_speaker
SBOM_URL=	https://www.FreeBSD.org
