SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display and update information about the top cpu processes
SBOM_LICENSE=	NOASSERTION
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/top
SBOM_URL=	https://www.FreeBSD.org
