SBOM_NAME=	${PACKAGE}
SBOM_DESC=	FreeBSD libc
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause AND BSD-1-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libc
SBOM_URL=	https://www.FreeBSD.org
SBOM_VERSION=	15.0
