SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Initialize, write, seek and extract data from a fifolog
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/fifolog/fifolog_create
SBOM_URL=	https://www.FreeBSD.org
