SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Dump multicast group management statistics per interface
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/ifmcstat
SBOM_URL=	https://www.FreeBSD.org
