SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Load firmware for Atheros USB wireless devices
SBOM_LICENSE=	NOASSERTION
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/uathload
SBOM_URL=	https://www.FreeBSD.org
