SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Off line print
SBOM_LICENSE=	BSD-4-Clause-UC AND LicenseRef-scancode-unknown-license-reference
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/lpr/lpr
SBOM_URL=	https://www.FreeBSD.org
