SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Report System V interprocess communication facilities status
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ipcs
SBOM_URL=	https://www.FreeBSD.org
