SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Communicate on SPI bus with slave devices
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/spi
SBOM_URL=	https://www.FreeBSD.org
