SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Trace command execution with boottrace(4)
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/boottrace
SBOM_URL=	https://www.FreeBSD.org
