SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Construct argument list(s) and execute utility
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/xargs
SBOM_URL=	https://www.FreeBSD.org
