SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control hardware performance monitoring counters
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pmccontrol
SBOM_URL=	https://www.FreeBSD.org
