SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Convert font files for use by the video console
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/vtfontcvt
SBOM_URL=	https://www.FreeBSD.org
