SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Create an error message file by massaging C source
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/mkstr
SBOM_URL=	https://www.FreeBSD.org
