SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Load firmware for Broadcom BCM2033 Bluetooth USB devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/bcmfw
SBOM_URL=	https://www.FreeBSD.org
