SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configuration utility for the concatenated disk driver
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ccdconfig
SBOM_URL=	https://www.FreeBSD.org
