SBOM_NAME=	${PACKAGE}
SBOM_DESC=	DOS/Windows (FAT) file system consistency checker
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/fsck_msdosfs
SBOM_URL=	https://www.FreeBSD.org
