SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure PWM (Pulse Width Modulation) hardware
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pwm
SBOM_URL=	https://www.FreeBSD.org
