SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Fold long lines for finite width output device
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/fold
SBOM_URL=	https://www.FreeBSD.org
