SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Perform various studies on a system's overall PMCs
SBOM_LICENSE=	LicenseRef-scancode-bsd-unchanged
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pmcstudy
SBOM_URL=	https://www.FreeBSD.org
