SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Utility for managing LSI Fusion-MPT controllers
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/mptutil
SBOM_URL=	https://www.FreeBSD.org
