SBOM_NAME=	${PACKAGE}
SBOM_DESC=	CAM data transfer utility
SBOM_LICENSE=	LicenseRef-scancode-intel-bsd-2-clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/camdd
SBOM_URL=	https://www.FreeBSD.org
