SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Performance measurement with performance monitoring hardware
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pmcstat
SBOM_URL=	https://www.FreeBSD.org
