SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Encode / decode a binary file
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/bintrans
SBOM_URL=	https://www.FreeBSD.org
