SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Device and resource information utility library
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libdevinfo
SBOM_URL=	https://www.FreeBSD.org
