SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Set local timezone
SBOM_LICENSE=	LicenseRef-scancode-mit-license-1998
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/tzsetup
SBOM_URL=	https://www.FreeBSD.org
