SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library for manipulating smart buffers
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libsbuf
SBOM_URL=	https://www.FreeBSD.org
