SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Line printer control program
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/lpr/lpc
SBOM_URL=	https://www.FreeBSD.org
