SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library for mainipulate capability modes
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libcasper/libcasper
SBOM_URL=	https://www.FreeBSD.org
