SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Query routing daemons for their routing tables
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/routed/rtquery
SBOM_URL=	https://www.FreeBSD.org
