SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control utility for the disk partitioning GEOM class
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/geom/part
SBOM_URL=	https://www.FreeBSD.org
