SBOM_NAME=	${PACKAGE}
SBOM_DESC=	ISCSI initiator management utility
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/iscsictl
SBOM_URL=	https://www.FreeBSD.org
