SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display or modify contents of the EEPROM or NVRAM
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/nvram
SBOM_URL=	https://www.FreeBSD.org
