SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Router solicitation daemon
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/rtsold
SBOM_URL=	https://www.FreeBSD.org
