SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Bluetooth HCI configuration utility
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/hccontrol
SBOM_URL=	https://www.FreeBSD.org
