SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library for creating, destroying and modifying ZFS boot environments
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libbe
SBOM_URL=	https://www.FreeBSD.org
