SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure and mount an in-memory file system using the md(4) driver or the tmpfs(4) filesystem
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/mdmfs
SBOM_URL=	https://www.FreeBSD.org
