SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Change standard streams initial buffering
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/stdbuf
SBOM_URL=	https://www.FreeBSD.org
