SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Change an ELF binary's feature control note
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/elfctl
SBOM_URL=	https://www.FreeBSD.org
