SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Generate a patch between two binary files
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/bsdiff/bsdiff
SBOM_URL=	https://www.FreeBSD.org
