SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Install firmware packages for the running system
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/fwget
SBOM_URL=	https://www.FreeBSD.org
