SBOM_NAME=	${PACKAGE}
SBOM_DESC=	System video console keyboard control/configuration utility
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/kbdcontrol
SBOM_URL=	https://www.FreeBSD.org
