SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Be notified if mail arrives and who it is from
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/biff
SBOM_URL=	https://www.FreeBSD.org
