SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure the dynamic linker search path for shared libraries
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ldconfig
SBOM_URL=	https://www.FreeBSD.org
