SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control system cache behaviour with respect to memory
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/memcontrol
SBOM_URL=	https://www.FreeBSD.org
