SBOM_NAME=	${PACKAGE}
SBOM_DESC=	C++ ABI implementation providing low-level support for a standard C++ library
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://github.com/libcxxrt/libcxxrt/tree/6f2fdfebcd6291d763de8b17740d636f01761890
SBOM_URL=	https://github.com/libcxxrt/libcxxrt
