SBOM_NAME=	${PACKAGE}
SBOM_DESC=	File system consistency check and interactive repair
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/fsck
SBOM_URL=	https://www.FreeBSD.org
