SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Execute a utility with an altered default network view
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/setfib
SBOM_URL=	https://www.FreeBSD.org
