SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Disables a pNFS data storage server (DS)
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pnfsdskill
SBOM_URL=	https://www.FreeBSD.org
