SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Link editor for BTX clients
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/btxld
SBOM_URL=	https://www.FreeBSD.org
