SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control POSIX shared memory segments
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/posixshmcontrol
SBOM_URL=	https://www.FreeBSD.org
