SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Cut out selected portions of each line of a file
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/cut
SBOM_URL=	https://www.FreeBSD.org
