SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Implementation of the SSL/TLS protocol (RFC 5246) written in C
SBOM_LICENSE=	MIT
SBOM_SOURCE=	https://bearssl.org/gitweb/?p=BearSSL;a=tree;h=d40d23b60cf1a42188a441b59226db35da234fea;hb=d40d23b60cf1a42188a441b59226db35da234fea
SBOM_URL=	https://bearssl.org
