SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control some process execution aspects
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/proccontrol
SBOM_URL=	https://www.FreeBSD.org
