SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Notify NFS servers about unmounted NFS file systems
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/rpc.umntall
SBOM_URL=	https://www.FreeBSD.org
