SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Show snapshot location on UFS file systems
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/snapinfo
SBOM_URL=	https://www.FreeBSD.org
