SBOM_NAME=	${PACKAGE}
SBOM_DESC=	User interface to the IPFilter pools
SBOM_LICENSE=	LicenseRef-scancode-other-permissive
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ipf/ippool
SBOM_URL=	https://www.FreeBSD.org
