SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Force propagation of updated NIS databases
SBOM_LICENSE=	BSD-4-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/yppush
SBOM_URL=	https://www.FreeBSD.org
