SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure DDB kernel debugger properties
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ddb
SBOM_URL=	https://www.FreeBSD.org
