SBOM_NAME=	${PACKAGE}
SBOM_DESC=	NFS file locking daemon
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/rpc.lockd
SBOM_URL=	https://www.FreeBSD.org
