SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Get core images of running process
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/gcore
SBOM_URL=	https://www.FreeBSD.org
