SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Run a guest operating system inside a virtual machine
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bhyve
SBOM_URL=	https://www.FreeBSD.org
