SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Execute a utility at an altered scheduling priority
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/nice
SBOM_URL=	https://www.FreeBSD.org
