SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library allows an application to generate text, XML, JSON, and HTML output using a common set of function calls.
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://github.com/Juniper/libxo/tree/1.4.0
SBOM_URL=	https://github.com/Juniper/libxo
