SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Queue, examine or delete jobs for later execution
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/at
SBOM_URL=	https://www.FreeBSD.org
