SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Adjust real-time clock (rtc) and kernel timezone offset
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/adjkerntz
SBOM_URL=	https://www.FreeBSD.org
