SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Run detached from the controlling terminal
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/daemon
SBOM_URL=	https://www.FreeBSD.org
