SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Merge corresponding or subsequent lines of files
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/paste
SBOM_URL=	https://www.FreeBSD.org
