SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Bluetooth Service Discovery Protocol query utility
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/sdpcontrol
SBOM_URL=	https://www.FreeBSD.org
