SBOM_NAME=	${PACKAGE}
SBOM_DESC=	CAM Target Layer control utility
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/ctladm
SBOM_URL=	https://www.FreeBSD.org
