SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print system accounting statistics
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/sa
SBOM_URL=	https://www.FreeBSD.org
