SBOM_NAME=	${PACKAGE}
SBOM_DESC=	BSD licensed ELF toolchain
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://sourceforge.net/p/elftoolchain/code/
SBOM_URL=	https://sourceforge.net/projects/elftoolchain/
