SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Modify a running virtual_oss(8) instance's options
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/virtual_oss/virtual_oss_cmd
SBOM_URL=	https://www.FreeBSD.org
