SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Decrypt a core dump of the operating system
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/decryptcore
SBOM_URL=	https://www.FreeBSD.org
