SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Return filename or directory portion of pathname
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/basename
SBOM_URL=	https://www.FreeBSD.org
