SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Enable/disable system accounting
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/accton
SBOM_URL=	https://www.FreeBSD.org
