SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display and modify floppy disk parameters
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/fdcontrol
SBOM_URL=	https://www.FreeBSD.org
