SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print the values of all keys in a NIS database
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ypcat
SBOM_URL=	https://www.FreeBSD.org
