SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control (start/stop/etc.) or list system services
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/service
SBOM_URL=	https://www.FreeBSD.org
