SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Load user and group information into the kernel for NFSv4 services plus support manage-gids for all NFS versions
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/nfsuserd
SBOM_URL=	https://www.FreeBSD.org
