SBOM_NAME=	${PACKAGE}
SBOM_DESC=	User information lookup program
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/finger
SBOM_URL=	https://www.FreeBSD.org
