SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Manage updates to system files not updated by installworld
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/etcupdate
SBOM_URL=	https://www.FreeBSD.org
