SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print a random, hopefully interesting, adage
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/fortune/fortune
SBOM_URL=	https://www.FreeBSD.org
