SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Analyze a core dump of the operating system
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/crashinfo
SBOM_URL=	https://www.FreeBSD.org
