SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Network RIP and router discovery routing daemon
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/routed
SBOM_URL=	https://www.FreeBSD.org
