SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library for password database operations in capability mode
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libcasper/services/cap_pwd
SBOM_URL=	https://www.FreeBSD.org
