SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Internet domain name and network number directory service
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/whois
SBOM_URL=	https://www.FreeBSD.org
