SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Load firmware for Intel Wireless AC Bluetooth USB devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/iwmbtfw
SBOM_URL=	https://www.FreeBSD.org
