SBOM_NAME=	${PACKAGE}
SBOM_DESC=	RFCOMM Serial Port Profile daemon
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/bluetooth/rfcomm_sppd
SBOM_URL=	https://www.FreeBSD.org
