SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Run a shell command on a named attribute directory
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/runat
SBOM_URL=	https://www.FreeBSD.org
