SBOM_NAME=	${PACKAGE}
SBOM_DESC=	User interface for firewall, traffic shaper, packet scheduler, in-kernel NAT.
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ipfw
SBOM_URL=	https://www.FreeBSD.org
