SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Fetch and install binary updates to FreeBSD
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/freebsd-update
SBOM_URL=	https://www.FreeBSD.org
