SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Extract strings from C programs to implement shared strings
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/xstr
SBOM_URL=	https://www.FreeBSD.org
