SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Userspace companion to Chelsio cxgbe Ethernet driver
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/cxgbetool
SBOM_URL=	https://www.FreeBSD.org
