SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Fill in the backtrace of the currently executing thread
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://github.com/NetBSD/src/tree/1c512be1f7a3bda2d36a9790dcaa63d0161b1ed7/lib/libexecinfo
SBOM_URL=	https://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libexecinfo/
