SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print a dependency ordering of interdependent files
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/rcorder
SBOM_URL=	https://www.FreeBSD.org
