SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Open source PAM library that focuses on simplicity, correctness, and cleanliness.
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://git.des.dev/OpenPAM/OpenPAM/src/commit/7a0660d699c4f82aa234524256b5b9f5a7cba786
SBOM_URL=	https://openpam.org
