SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Show network status and statistics
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/netstat
SBOM_URL=	https://www.FreeBSD.org
