SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Report or filter out repeated lines in a file
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/uniq
SBOM_URL=	https://www.FreeBSD.org
