SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Set environment and execute command, or print environment
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/env
SBOM_URL=	https://www.FreeBSD.org
