SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Mylex DAC-family RAID management utility
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/mlxcontrol
SBOM_URL=	https://www.FreeBSD.org
