SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display the system message buffer
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/dmesg
SBOM_URL=	https://www.FreeBSD.org
