SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Utility and a library to build scripts and tools with TUI dialogs and widgets
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://gitlab.com/alfix/bsddialog/-/tree/1.1
SBOM_URL=	https://gitlab.com/alfix/bsddialog
SBOM_VERSION=	1.1
