SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Displays a calendar and the date of Easter
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ncal
SBOM_URL=	https://www.FreeBSD.org
