SBOM_NAME=	${PACKAGE}
SBOM_DESC=	System video console keyboard map/font dialog utilities
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/kbdmap
SBOM_URL=	https://www.FreeBSD.org
