SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Restore files or file systems from backups made with dump
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/restore
SBOM_URL=	https://www.FreeBSD.org
