SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Dump all meta information of an existing ufs file system
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ffsinfo
SBOM_URL=	https://www.FreeBSD.org
