SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control utility for virtual data storage devices
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/geom/virstor
SBOM_URL=	https://www.FreeBSD.org
