SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Simple tools for querying SNMP agents
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bsnmpd/tools/bsnmptools
SBOM_URL=	https://www.FreeBSD.org
