SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Boot manager installation/configuration utility
SBOM_LICENSE=	BSD-2-Clause AND BSD-1-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/boot0cfg
SBOM_URL=	https://www.FreeBSD.org
