SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library missing description
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause AND BSD-1-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/csu
SBOM_URL=	https://www.FreeBSD.org
