SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display (do not display) messages from other users
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/mesg
SBOM_URL=	https://www.FreeBSD.org
