SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure network interface parameters
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause AND BSD-2-Clause-FreeBSD AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ifconfig
SBOM_URL=	https://www.FreeBSD.org
