SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Create a random access file for storing strings
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/fortune/strfile
SBOM_URL=	https://www.FreeBSD.org
