SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Mount an MS-DOS (FAT) file system
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/mount_msdosfs
SBOM_URL=	https://www.FreeBSD.org
