SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Universal addresses to RPC program number mapper
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/rpcbind
SBOM_URL=	https://www.FreeBSD.org
