SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Configure address selection policy for IPv6 and IPv4
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/ip6addrctl
SBOM_URL=	https://www.FreeBSD.org
