SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Magic number recognition library
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	http://ftp.astron.com/pub/file/file-5.46.tar.gz
SBOM_URL=	https://www.darwinsys.com/file/
SBOM_VERSION=	5.46
