SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Indent and format C program source
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/indent
SBOM_URL=	https://www.FreeBSD.org
