SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display account information
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/logins
SBOM_URL=	https://www.FreeBSD.org
