SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Firewall-like access controls for file system objects
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/ugidfw
SBOM_URL=	https://www.FreeBSD.org
