SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Create, remove, modify & display system users and groups
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pw
SBOM_URL=	https://www.FreeBSD.org
