SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Specify audit configurations on a process
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/setaudit
SBOM_URL=	https://www.FreeBSD.org
