SBOM_NAME=	${PACKAGE}
SBOM_DESC=	System video console control and configuration utility
SBOM_LICENSE=	BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/vidcontrol
SBOM_URL=	https://www.FreeBSD.org
