SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Sources printout with inlined profiling
SBOM_LICENSE=	LicenseRef-scancode-bsd-unmodified
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/pmcannotate
SBOM_URL=	https://www.FreeBSD.org
