SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Reports on packet filter statistics and filter list
SBOM_LICENSE=	LicenseRef-scancode-other-permissive
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ipf/ipfstat
SBOM_URL=	https://www.FreeBSD.org
