SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Magnetic tape manipulating program
SBOM_LICENSE=	BSD-3-Clause AND LicenseRef-scancode-intel-bsd-2-clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/mt
SBOM_URL=	https://www.FreeBSD.org
