SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display disk usage and limits
SBOM_LICENSE=	BSD-4-Clause AND BSD-3-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/quota
SBOM_URL=	https://www.FreeBSD.org
