SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Show Bluetooth sockets information
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/bluetooth/btsockstat
SBOM_URL=	https://www.FreeBSD.org
