SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print kernel state as Prometheus metrics
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/prometheus_sysctl_exporter
SBOM_URL=	https://www.FreeBSD.org
