SBOM_NAME=	${PACKAGE}
SBOM_DESC=	User interface to the NAT
SBOM_LICENSE=	LicenseRef-scancode-other-permissive
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/sbin/ipf/ipnat
SBOM_URL=	https://www.FreeBSD.org
