SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Mouse protocol conversion daemon
SBOM_LICENSE=	BSD-4-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/moused/msconvd
SBOM_URL=	https://www.FreeBSD.org
