SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print information about system device configuration
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/devinfo
SBOM_URL=	https://www.FreeBSD.org
