SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Display call graph profile data
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/gprof
SBOM_URL=	https://www.FreeBSD.org
