SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Return hostname of NIS server of map master
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ypwhich
SBOM_URL=	https://www.FreeBSD.org
