SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library permits creating and managing name value pairs
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libnv
SBOM_URL=	https://www.FreeBSD.org
