SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print sequential or random data
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/jot
SBOM_URL=	https://www.FreeBSD.org
