SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Print the values of one or more keys in a NIS database
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ypmatch
SBOM_URL=	https://www.FreeBSD.org
