SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library for configure network interface parameters
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libifconfig
SBOM_URL=	https://www.FreeBSD.org
