SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Library provides multi-byte character conversion tables for kernel side
SBOM_LICENSE=	BSD-4-Clause and BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/lib/libkiconv
SBOM_URL=	https://www.FreeBSD.org
