SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Bluetooth Service Discovery Protocol daemon
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bluetooth/sdpd
SBOM_URL=	https://www.FreeBSD.org
