SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Get information about disk device
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/diskinfo
SBOM_URL=	https://www.FreeBSD.org
