SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Tool for managing trusted and untrusted TLS certificates
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/certctl
SBOM_URL=	https://www.FreeBSD.org
