SBOM_NAME=	${PACKAGE}
SBOM_DESC=	CAM Target Layer statistics utility
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/ctlstat
SBOM_URL=	https://www.FreeBSD.org
