SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Control POSIX mqueuefs message queues
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/posixmqcontrol
SBOM_URL=	https://www.FreeBSD.org
