SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Sort or merge records (lines) of text and binary files
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/sort
SBOM_URL=	https://www.FreeBSD.org
