SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Load a FreeBSD guest inside a bhyve virtual machine
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/bhyveload
SBOM_URL=	https://www.FreeBSD.org
