SBOM_NAME=	${PACKAGE}
SBOM_DESC=	System messages and junk mail program
SBOM_LICENSE=	BSD-3-Clause AND BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.bin/msgs
SBOM_URL=	https://www.FreeBSD.org
