SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Utility for managing LSI Fusion-MPT 2/3 controllers
SBOM_LICENSE=	BSD-2-Clause
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/mpsutil
SBOM_URL=	https://www.FreeBSD.org
