SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Snoop on another tty line
SBOM_LICENSE=	LicenseRef-scancode-other-permissive
SBOM_SOURCE=	https://cgit.freebsd.org/src/tree/usr.sbin/watch
SBOM_URL=	https://www.FreeBSD.org
